### ISSUE TITLE
Variables as User Codes - Enhancement

### ISSUE THREAD

**Issue by 7RDR7** [bla260/ad2usb#24]
It would be a nice enhancement to use variables as user codes? The idea would be the ability to change the Ademco user codes via the AD2USB plugin using Indigo variables. This would be similar to how the "Z-wave Lock Manager" plugin manages door codes. You can change the codes today within Indigo, but only by entering the code, not using a variable.

**Comment by bla260** [comment]
Within the plugin, user codes are currently only used in Trigger User Events, aka “User Actions” (Arm Away, Arm Stay, or Disarm). Adding an option to use a variable here in addition to entering the user code is a good enhancement. To make sure I understand, an example is  you could define a variable “Fred_User_Code” with the value of “32” and then use that variable in the Trigger in lieu of entering a user code. 

You can also write arbitrary messages to the panel and that Action could be changed to support variables in addition to text. That is another good enhancement.

But I think you’re asking for more than that. On the actual alarm panel, User codes are managed by entering the master code + 8 and the various options associated with user codes (Add, Delete, Partitions, Authority Levels, etc.). 

Are you looking for pre-defined Indigo actions that run pre-defined User commands?  If so, the Master Code is required for those commands.

**Comment by 7RDR7** [comment]
Thanks, yes to all scenarios, including master code

**Comment by 7RDR7** [comment]
Didn’t mean to send yet…. Yeah, I do that with the door locks, but I guess the difference is that the panel requires the master code each time. I’m trying to synchronize the door lock and the panel codes for temporary users.

**Comment by bla260** [comment]
I’ve created a branch user-events-triggers to make these changes. This may be the next release (3.3) around end of September. This will end up consolidating user events into alarm events.

**Comment by 7RDR7** [comment]
Thanks! Out of town, but I’ll give it a try when I get back.

Ron Robinson
(703) 568-9330

**Comment by bla260** [comment]
Release 3.3.0 is out. It allows a variable to be used in the Action "Write To Panel". It also can detect User Actions (Arm, Disarm, ...) based on a variable. I think the first feature is all you need to construct Triggers and create Action Groups to do what you need to. Let me know via the Forum if this is not sufficient.

**Comment by 7RDR7** [comment]
Thanks! Great enhancement!
